version: 2
workflows:
  version: 2
  all:
    jobs:
      - node-latest
      - node10:
          requires:
            - node-latest
      - node9:
          requires:
            - node-latest
      - node8:
          requires:
            - node-latest
      - node6:
          requires:
            - node-latest
      - release:
          filters:
            branches:
              only: master
          requires:
            - node-latest
            - node10
            - node9
            - node8
            - node6
jobs:
  local-test:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - run: npm run verify
  node-latest:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      # - restore_cache:
      #     name: Restore node_modules cache
      #     key: yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: |
            if [ ! -d node_modules ]; then
              yarn install
              npx lerna add jest-junit packages/uni-cli
            fi
      # - save_cache:
      #     name: Save node modules cache
      #     key: yarn-{{ checksum "yarn.lock" }}
      #     paths:
      #       - 'node_modules'
      #       - 'packages/uni-cli/node_modules'
      - persist_to_workspace:
          root: '.'
          paths:
            - 'node_modules'
            - 'packages/uni-cli/node_modules'
      - run: cd packages/uni-cli && yarn run verify:ci
      - run: cd packages/uni-cli && npx codecov
      - store_test_results:
          path: packages/uni-cli/.reports/junit
  node10:
    docker:
      - image: 'circleci/node:9'
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - run: cd packages/uni-cli && yarn run verify:ci
      - store_test_results:
          path: packages/uni-cli/.reports/junit
  node9:
    docker:
      - image: 'circleci/node:9'
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - run: cd packages/uni-cli && yarn run verify:ci
      - store_test_results:
          path: packages/uni-cli/.reports/junit
  node8:
    docker:
      - image: 'circleci/node:8'
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - run: cd packages/uni-cli && yarn run verify:ci
      - store_test_results:
          path: packages/uni-cli/.reports/junit
  node6:
    docker:
      - image: 'circleci/node:6'
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - run: cd packages/uni-cli && yarn run verify:ci
      - store_test_results:
          path: packages/uni-cli/.reports/junit
  release:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - run: npm i --no-save greenkeeper-lockfile
      - run:
          name: update greenkeeper lockfile
          command: ./node_modules/.bin/greenkeeper-lockfile-update
      - run: cd packages/uni-cli && npm run build
      - run:
          name: upload greenkeeper lockfile
          command: ./node_modules/.bin/greenkeeper-lockfile-upload
      # - run: npx lerna exec --concurrency 1 -- npx semantic-release -e semantic-release-monorepo
